### ISSUE TITLE
💡 Ctrl+Backspace to delete entire word

### ISSUE THREAD

**Issue by Geggman** [kraanzu/termtyper#1]
It is really comfortable to delete an entire word when you made a lot of mistakes.

**Comment by Kritiqual** [comment]
Or `ctrl + w`

**Comment by kraanzu** [comment]
@Geggman 
> It is really comfortable to delete an entire word when you made a lot of mistakes.

Yeah about that, there is currently no way for detection of ctrl+backspace 
in textual right now.
The backspace is also detected as ctrl+h.. as you can see [here](https://github.com/kraanzu/termtyper/blob/9da5010f8349bd8bf487b5b48042d769c8e79c17/src/termtyper/ui/widgets/screen.py#L267)

I am thinking of creating a config file where user can create their own theme as well as set some keybindings? 
like @Kritiqual mentioned `ctrl+w` for example..

**Comment by kraanzu** [comment]
Closing this issue as `ctrl+w` is added 
Happy Typing :)
