### ISSUE TITLE
Disabling type speed when typing 

### ISSUE THREAD

**Issue by luravoid** [kraanzu/termtyper#12]
Hi, Is there a possibility to disable these numbers at the top when typing? i find it distracting
![image](https://user-images.githubusercontent.com/103893901/171988843-6c3ef63d-d1a2-4adc-ad8c-32aee00e4f97.png)

**Comment by kraanzu** [comment]
Yeah actually I am planning to add different themes both for the bar and the typing space in the next release
So You'll be able to choose the bar theme then... i.e. both the current and the `minimal` version you asked

**Comment by kraanzu** [comment]
Hey @luravoid, you can now do that by pressing `ctrl+d`
