### ISSUE TITLE
💡 [FEAT] letter capitalization

### ISSUE THREAD

**Issue by drjaska** [kraanzu/termtyper#22]
From what I can see the current word casing is all lowercase. It would be nice to have capitalization like word Word WORD.

Maybe options for WritingInCamelCase and writing_in_snake_case for coders.

**Comment by kraanzu** [comment]
Yes I can make a toggle menu for that too :)

**Comment by kraanzu** [comment]
@somenothing pushed a feature which allows you to select 3 levels for capitalization.
So I'll close this issue :)

```
off: All lowercase words, don't worry about your 'Shift' key
on : You will come across some words that start with a capital letter, but not many
max: Try a mixed-case word trial
```
