### ISSUE TITLE
[BUG] punctuation can cause too many space inputs

### ISSUE THREAD

**Issue by drjaska** [kraanzu/termtyper#23]
When punctuation is enabled and currently being asked for typing a space instead jumps to the start of the next word inserting 2 spaces with a single press and trains bad backspace muscle memory.

**Comment by kraanzu** [comment]
`It's not a bug... It's a feature` XD
Jokes aside, I think you are talking about how pressing space jumps to the starting of next word...
You can use force correct` but then you won't be able to move until you've pressed the correct key.
Ig I'll that to the setting to :)

**Comment by drjaska** [comment]
Wait why are non-complete words allowed and how is partial word completion handled? It's not just punctuation which prompts this behavior.

**Comment by kraanzu** [comment]
> Wait why are non-complete words allowed

Well, sometimes you might wanna skip a word.. so yeah.. it's there :)

> how is partial word completion handled?

I just can't ignore the skipped letters so there are treated as wrongly-typed. 

Monkeytype provides this option so i did too :)

**Comment by drjaska** [comment]
Oh, so it is a feature and not a bug. The way I discovered it felt unintuitive and like a bug. :D
