### ISSUE TITLE
💡 Highest Score mentioned after each try

### ISSUE THREAD

**Issue by bnkc** [kraanzu/termtyper#27]
I think it would be neat to see your highest score amongst the "raw speed, corrected speed, accuracy, time taken, *Highest score*".

Let me know if you want to implement this and I can actually fork the repo and add it myself. would be great practice for me. Let me know! Thanks :)

**Comment by kraanzu** [comment]
That would be a great idea!

> Let me know if you want to implement this

Sure, Go ahead :)
If you have any questions, feel free to ping :smile:

**Comment by kraanzu** [comment]
Closing this as #32 is merged
