### ISSUE TITLE
🐛 Keypress sound not working

### ISSUE THREAD

**Issue by wasi-master** [kraanzu/termtyper#4]
**Describe the bug** 🐛
When pressing a key, instead of a sound coming, it shows an error at the bottom of the screen

**To Reproduce** 🐣
1. Enable the sound option
2. Type some text
3. See error

**Expected behavior**  🤔 
It should play the keypress sound

**Screenshots** 🧐
![gif](https://i.ibb.co/bNzsWY1/termtyper.gif)
A still image of the error (from the gif)
![image](https://user-images.githubusercontent.com/63045920/162124085-3829dfce-f7ef-411f-90f8-42705cda2dbc.png)

**Desktop (please complete the following information):**  🤖
 - OS: Windows 11
 - Version 22H2 (22581.200)

**Additional context** 📝
It seems like the file path being passed to playsound is from the python 3.9 directory instead of being in the python 3.10 one where I installed termtyper. I've uninstalled playsound and termtyper from python 3.9, I only have them in python 3.10 but this still occurs.
![image](https://user-images.githubusercontent.com/63045920/162124311-6f7d0600-73bc-400d-b596-c32e695d6062.png)

<details><summary>File Tree</summary>

**Python 3.10**\
Contains the sounds required
![image](https://user-images.githubusercontent.com/63045920/162124670-f5ad1ca7-e2ea-4a22-a6b3-40a781ea3c59.png)

**Python 3.9**\
Doesn't even have the termtyper directory
![image](https://user-images.githubusercontent.com/63045920/162124465-fd52851a-c96a-483c-9a7e-32118cd33a24.png)
</details>

This line seems to be the problem

https://github.com/kraanzu/termtyper/blob/9da5010f8349bd8bf487b5b48042d769c8e79c17/src/termtyper/utils/parser.py#L26-L35

This assumes the pip command is always going to be from the python interpreter termtyper is installed in. In my case, I have the pip command set to python 3.9, so the rich location shown by `pip show rich` is the one from that, for python 3.9 it would need to run `py -3.10 -m pip show rich`, but why does it even need to run these commands? just to get the path where termtyper is installed? for that you can just use the following snippet:

```python
import os.path

sounds = os.path.join(os.path.dirname(__file__), "sounds", "mech.wav")
```
This is what I use in my [`pypi-command-line` package](https://github.com/wasi-master/pypi-command-line/blob/main/pypi_cli/__main__.py#L39-L41) and it works great.

I just realized that I can set `sounds_loc` in my config but it should set the location automatically though

**Comment by wasi-master** [comment]
Manually changing the sounds_loc in my config raises another error 😫

![image](https://user-images.githubusercontent.com/63045920/162129316-9da25c3d-8765-4f7e-afc1-5db156b7ba26.png)

**Comment by kraanzu** [comment]
That works great !!!
Thank you so much @wasi-master for the insight! :nerd_face: 
The lag for the first time startup is gone too :)
I am pushing the updates now...you can recheck <3

**Comment by wasi-master** [comment]
Thanks for the quick fix :)
