### ISSUE TITLE
[BUG] Capitalization mode doesn't seem to work?

### ISSUE THREAD

**Issue by vymague** [kraanzu/termtyper#41]
I just installed it from AUR.  

Under Settings > Capitalization Mode, I tried both "on" and "max" settings. But I didn't see any capitalized letters when I entered "Start Typing!". 

Perhaps I should activate it somehow?  

Note: I don't know why this post doesn't have the "bug" label. And I don't know how to edit it in.

**Comment by somenothing** [comment]
I guess this is a problem that termtyper does not update the modified config file in time. I'm trying to fix it.

**Comment by vymague** [comment]
Seems to work fine now.
