### ISSUE TITLE
[BUG] Toggle numbers ctrl+n and toggle punctuations ctrl+p don't work?

### ISSUE THREAD

**Issue by vymague** [kraanzu/termtyper#42]
**Describe the bug** 🐛
When I pressed those keybindings, the desired effect didn't happen. For example typing "ctrl+n" twice, but both produced texts still show numbers.

**To Reproduce** 🐣
1. Go to "Start Typing!".  
2. Press "ctrl+n" or "ctrl+p".  
3. Observe that the texts still contain numbers or punctuations.  

**Expected behavior**  🤔 
I expected the keybindings would remove the numbers and punctuation respectively.  

**Desktop (please complete the following information):**  🤖
 - OS: Linux
 - Version: v2.0.0, installed from termtyper-git package on AUR

**Comment by kraanzu** [comment]
Hey @vymague,
This was due to improper handling of strings and booleans...should be fixed now... If you still have issues feel free to re-open
