### ISSUE TITLE
💡 [FEAT] Add unit testing/automated testing for devs

### ISSUE THREAD

**Issue by ponderstine** [kraanzu/termtyper#45]
**Is your feature request related to a problem? 😢 Please describe.** 
Add unit testing/automated testing

**Describe the solution you'd like**   🤔
Add unit testing/automated testing via PyTest/PyUnit/similar dependency to allow open source devs to work remotely and asynchronously while maintaining the quality of code and ability to build this project without bugs. This can be automated easily with GitHub Actions and a build workflow that is required to pass before a PR will be merged.

**Describe alternatives you've considered**  🧐
Every dev could have their own independent testing procedures in their local environment but this would lead to great repetition of work, opportunities for new bugs to be added to different dev's builds and/or test code, and general lack of cohesion in the project.

**Additional context** 📝
I want to be able to test things without breaking what is already there. I saw in the .gitignore file to ignor a /test folder but if anyone does have any test code available I would really appreciate and think it is a good idea to merge that in.

**Comment by kraanzu** [comment]
I already have checks for code formatting and build runs..
I didn't make tests for internal testing as I was not sure how to go about it :)
If you have any ideas or if you might wanna add tests, You are more than welcome to do so :)

**Comment by ponderstine** [comment]
sounds great! I mostly saw that any testing might be hidden from the git repo and wanted access to it if there was any but if I create any testing I will make sure to include that and it can possibly get merged in as well. Thanks! 👍🏻
