### ISSUE TITLE
[BUG]  ERROR: Package 'termtyper' requires a different Python: 3.8.8 not in '<4.0,>=3.10'

### ISSUE THREAD

**Issue by WQZ0712** [kraanzu/termtyper#47]
**Describe the bug** 🐛
I don't know Python so  I need some help
I use git clone newest code and install python3.8.8. 
There are some problems to pip3 install .

**Screenshots** 🧐
![image](https://user-images.githubusercontent.com/33918180/184178087-07145f93-9fef-4818-a2f0-c77233e1ccad.png)

![image](https://user-images.githubusercontent.com/33918180/184176945-1e99cffa-497a-4b64-bbe5-6409f2956e34.png)

**Desktop (please complete the following information):**  🤖
windows

**Comment by kraanzu** [comment]
You'll need at least python version 3.10 to run termtyper, which in your case is 3.8.

**Comment by WQZ0712** [comment]
Oh, thank you，I get it
