### ISSUE TITLE
💡 Add live typing stats

### ISSUE THREAD

**Issue by alec-kr** [kraanzu/termtyper#5]
**Live typing stats 💡**
 
I think it would be beneficial if the user can get an idea of their current performance while typing.
This can be done by implementing a small dashboard below the typing section of the GUI. (See mockup diagram)

This dashboard could illustrate some typing statistics such as:
- The number of words that have been typed (e.g. "Words typed: 34")
- The number of words left in the paragraph (e.g. "Words left: 43")
- Elapsed time (e.g. "Time: 45s")

**Mockup diagram**  🧐
This mockup is what the first design iteration of the dashboard may look like.
![mockup drawio](https://user-images.githubusercontent.com/52685467/162324128-c22508f9-5a10-4ab4-9222-3c8cee54a743.png)

**Comment by kraanzu** [comment]
Yes I was thinking the same thing too.
I guess I can add a setting which allows user to keep the top bar of his choice? 
Like:
minimal: the current dashboard which shows a bar with color depending upon user's speed
verbose: the kind of dashboard you mentioned
How does that sound?

**Comment by alec-kr** [comment]
> I guess I can add a setting which allows user to keep the top bar of his choice?

Yes. This is a good suggestion. It will be an additional level of customization in the application.

> How does that sound?

It sounds great. Can I take up this issue? I can start the programming this weekend.

**Comment by kraanzu** [comment]
Sure thing :)
I am assigning you to this then. If you need any kind of help, don't hesitate to ask :)

**Comment by alec-kr** [comment]
Thank you for assigning me the issue. I will get started this weekend

**Comment by alec-kr** [comment]
@kraanzu Is there any way the ```render(self)``` function in race_bar.py can be modified to return two Panels instead of just one?

**Comment by alec-kr** [comment]
@kraanzu I have just submitted a PR.

**Comment by kraanzu** [comment]
yes :)
