### ISSUE TITLE
💡 [FEAT] Possibilty to switch language to generate the typing paragraph

### ISSUE THREAD

**Issue by periodLeo** [kraanzu/termtyper#50]
**Is your feature request related to a problem? 😢 Please describe.** 
Being able to change language settings in order to generate words from other language than English i.e. exercise typing by writting french, german, spanish, ... words

**Describe the solution you'd like**   🤔
Going to misc settings, switching language and then every paragraph you'll get will only use words of the desired language

**Describe alternatives you've considered**  🧐
I've figured out a solution locally consisting of creating a folder with a file for every language desired (english & french for the moment) and adding a "language" settings in Misc. It seems to work well for the moment, I can fork the project and open a PR if you are interested by this feature ! 

**Additional context** 📝
In order to add any other language you just have to create a language_words.py with a language_words variable in words folder,
then import the variable to generator.py, add a case to the switch case inside generate func, and finally add the option in the language setting in setting_options.py.

**Comment by kraanzu** [comment]
Hey there, thanks for opening this feature issue. 
Sounds great to me! I'll also start working on it now to make the UI better :) 

> I can fork the project and open a PR if you are interested by this feature !

Definitely! I'd really appreciate it :smiley: :heart: 

You can start working on it and if you need any kind of help from my side. Feel free to ping :)

**Comment by periodLeo** [comment]
PR done ! let me know if something doesn't seems right or doesn't match your way to code/do things !
