### ISSUE TITLE
💡 [FEAT] Add support to add languages via cmdline

### ISSUE THREAD

**Issue by kraanzu** [kraanzu/termtyper#55]
Language packs are quite big and just adding them all to the app will be too much bloat so the users can add languages manually using a cmd line flag

Here are the required tasks:

- [ ] Create a new page that lists all the languages ( from monkeytype :p )
- [x] Add a flag for eg `add` the language (Eg smassh add hindi)
- [x] The plugin should be located at termtyper/src/plugin/add_language.py
- [x] Store all the lang packs at termtyper/assets/languages/
- [x] Update CHANGELOG
- [ ] Update README

**Comment by kraanzu** [comment]
@duwudle assign

**Comment by duwudle** [comment]
Closing as it is implemented with PR #57
