### ISSUE TITLE
[BUG] AUR package is seriously broken

### ISSUE THREAD

**Issue by rhysperry111** [kraanzu/termtyper#6]
**Describe the bug** 🐛
The AUR package (`termtyper-git`) that you maintain for this project is seriously broken. It does the a pip install into the user's home (a serious problem, as it leaves left over files when uninstalled, and also means it will have to be installed via pip for other users anyway) and fails to list all the needed dependencies (pip).

**To Reproduce** 🐣
1. Try and install the package from the AUR
2. WTF
3. Audit the PKGBUILD
4. Die

**Expected behavior**  🤔 
1. Try and install the package from the AUR
2. :)

**Desktop (please complete the following information):**  🤖
 - OS: Arch Linux

**Additional context** 📝
If you need any help fixing the PKGBUILD, feel free to ask as I maintain a few AUR packages myself.

**Comment by kraanzu** [comment]
Yeah about that...It was my first try at building an AUR package and I seriously messed up.

> If you need any help fixing the PKGBUILD, feel free to ask as I maintain a few AUR packages myself.

Yes, that would be a great idea ;)

**Comment by rhysperry111** [comment]
Hey dw, it's all good. Once you learn how it's actually super useful - especially when you wanna build some random project but don't wanna mess around removing it afterwards.

Did kinda lose my chill this morning (was busy), so sorry about that.

I'll submit a fixed version of the PKGBUILD to you, and maybe add some comments on why certain things are done if needed :)

**Comment by kraanzu** [comment]
Hey @rhysperry111, just saw that there is an option to add co-maintainers in the AUR.. should I add you there?

**Comment by rhysperry111** [comment]
You could add me as a co-maintainer if you want, but here's a patch file for you to do it yourself anyway. You can apply it using `git apply`. (Had to append .txt to the filename because of github's supported filetypes)

[0001-Fix-PKGBUILD.patch.txt](https://github.com/kraanzu/termtyper/files/8459167/0001-Fix-PKGBUILD.patch.txt)
