### ISSUE TITLE
💡 [FEAT] Perhaps putting configuration file in ~/.config/termtyper?

### ISSUE THREAD

**Issue by Kritiqual** [kraanzu/termtyper#9]
**Describe the solution you'd like**   🤔
For better dotfiles control, I think you should make the default location of config file in `~/.config/termtyper/...`. 
That will keep my `~` clean

**Comment by rhysperry111** [comment]
Full compliance with the XDG spec isn't too hard. Just follow this basic logic:

- Check if `$XDG_CONFIG_HOME` is set
  - If yes, store configs in `$XDG_CONFIG_HOME/termtyper/...`
  - If no, check if `~/.config/` exists
    - If yes, store configs in `~/.config/termtyper/...`
    - If no, store configs in `~/.termtyper/...`

**Comment by rhysperry111** [comment]
Also a note, might wanna check for the old config file and possible move it to the new location
